### ISSUE TITLE
Bug in 1.3.21

### ISSUE THREAD

**Issue by darkfrog26** [pfn/android-sdk-plugin#165]
I was previously running in 1.3.20 just fine and after updating to 1.3.21 I get the following error when I try to compile:

```
[trace] Stack trace suppressed: run last ios/*:extractNatives for the full output.
[trace] Stack trace suppressed: run last android/*:extractNatives for the full output.
[error] (ios/*:extractNatives) java.lang.NoClassDefFoundError: Tasks$$anonfun$natives$3$$anonfun$apply$1
[error] (android/*:extractNatives) java.lang.NoClassDefFoundError: Tasks$$anonfun$natives$3$$anonfun$apply$1
[error] Total time: 6 s, completed Apr 23, 2015 10:28:50 AM
```

**Comment by pfn** [comment]
exit and re-start sbt

**Comment by pfn** [comment]
windows, mandatory locking OP

**Comment by darkfrog26** [comment]
Ah thanks, that did fix it. Sorry about that.

Also, for the record, I'm running Fedora.
